import crypto from "node:crypto";
import { Router } from "express";
import { Affiliate, AffiliateAuditLog, AffiliatePurchase, AffiliateReferral, AffiliateSettings } from "../models/index.js";
import { requireAdmin, requireMainAdmin } from "../middlewares/auth.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { AppError } from "../utils/AppError.js";
import { hashPassword } from "../utils/password.js";

export const affiliateMarketingRouter = Router();
affiliateMarketingRouter.use(requireAdmin, requireMainAdmin);
const actor = (req) => req.admin?._id?.toString();
async function settings() {
  let value = await AffiliateSettings.findOneAndUpdate({ key: "default" }, { $setOnInsert: { key: "default" } }, { upsert: true, new: true });
  if (value.referralBaseUrl === "https://kritamcqs.com") {
    value = await AffiliateSettings.findOneAndUpdate({ key: "default" }, { $set: { referralBaseUrl: "https://app.kritamcqs.com/affiliate" } }, { new: true });
    const affiliates = await Affiliate.find().select("affiliateCode");
    await Promise.all(affiliates.map((item) => Affiliate.updateOne({ _id: item._id }, { $set: { referralLink: `https://app.kritamcqs.com/affiliate?ref=${item.affiliateCode}` } })));
  }
  return value;
}
async function metrics(affiliateId) { const referralMatch = affiliateId ? { affiliateId } : {}; const purchaseMatch = affiliateId ? { affiliateId, paymentStatus: "PAID", subscriptionStatus: { $ne: "REFUNDED" } } : { paymentStatus: "PAID", subscriptionStatus: { $ne: "REFUNDED" } }; const [clicks, registrations, result] = await Promise.all([AffiliateReferral.countDocuments(referralMatch), AffiliateReferral.countDocuments({ ...referralMatch, userId: { $exists: true } }), AffiliatePurchase.aggregate([{ $match: purchaseMatch }, { $group: { _id: null, count: { $sum: 1 }, amount: { $sum: "$amount" } } }])]); const successfulPurchases = result[0]?.count || 0; const totalPurchaseAmount = result[0]?.amount || 0; return { clicks, registrations, successfulPurchases, totalPurchaseAmount, averagePurchaseValue: successfulPurchases ? totalPurchaseAmount / successfulPurchases : 0, conversionRate: registrations ? successfulPurchases / registrations * 100 : 0 }; }

affiliateMarketingRouter.get("/affiliate-marketing/dashboard", asyncHandler(async (_req, res) => { const [totalAffiliates, activeAffiliates, performance] = await Promise.all([Affiliate.countDocuments(), Affiliate.countDocuments({ status: "ACTIVE" }), metrics()]); res.json({ success: true, data: { totalAffiliates, activeAffiliates, ...performance } }); }));
affiliateMarketingRouter.get("/affiliate-marketing/affiliates", asyncHandler(async (_req, res) => { const items = await Affiliate.find().sort({ createdAt: -1 }); const stats = await Promise.all(items.map((item) => metrics(item._id))); res.json({ success: true, data: items.map((item, index) => ({ ...item.toJSON(), ...stats[index] })) }); }));
affiliateMarketingRouter.post("/affiliate-marketing/affiliates", asyncHandler(async (req, res) => { const body = req.body || {}; if (!body.email || !body.username || !body.password || !body.affiliateName) throw new AppError("Affiliate name, email, username and password are required", 400); if (String(body.password).length < 8) throw new AppError("Password must be at least 8 characters", 400); let code = String(body.affiliateCode || "").trim().toUpperCase(); if (code && !/^[A-Z0-9_-]{4,24}$/.test(code)) throw new AppError("Invalid affiliate code", 400); if (!code) { code = `AFF${String(await Affiliate.countDocuments() + 1).padStart(4, "0")}`; while (await Affiliate.exists({ affiliateCode: code })) code = `AFF${crypto.randomInt(1000, 999999)}`; } const config = await settings(); const affiliate = await Affiliate.create({ ...body, affiliateCode: code, passwordHash: hashPassword(body.password), referralLink: `${String(config.referralBaseUrl).replace(/\/$/, "")}/?ref=${code}` }); await AffiliateAuditLog.create({ adminId: actor(req), affiliateId: affiliate._id, action: "Affiliate Created", newData: affiliate.toJSON() }); res.status(201).json({ success: true, data: affiliate }); }));
affiliateMarketingRouter.patch("/affiliate-marketing/affiliates/:id", asyncHandler(async (req, res) => { const old = await Affiliate.findById(req.params.id); if (!old) throw new AppError("Affiliate not found", 404); const update = { ...req.body }; delete update.password; delete update.passwordHash; delete update.affiliateCode; delete update.referralLink; const affiliate = await Affiliate.findByIdAndUpdate(old._id, { $set: update }, { new: true, runValidators: true }); await AffiliateAuditLog.create({ adminId: actor(req), affiliateId: old._id, action: update.status ? `Affiliate ${update.status}` : "Affiliate Updated", oldData: old.toJSON(), newData: affiliate.toJSON() }); res.json({ success: true, data: affiliate }); }));
affiliateMarketingRouter.post("/affiliate-marketing/affiliates/:id/reset-password", asyncHandler(async (req, res) => { if (String(req.body?.password || "").length < 8) throw new AppError("Password must be at least 8 characters", 400); await Affiliate.findByIdAndUpdate(req.params.id, { passwordHash: hashPassword(req.body.password) }); await AffiliateAuditLog.create({ adminId: actor(req), affiliateId: req.params.id, action: "Password Reset" }); res.json({ success: true, message: "Password reset" }); }));
affiliateMarketingRouter.get("/affiliate-marketing/referrals", asyncHandler(async (_req, res) => res.json({ success: true, data: await AffiliateReferral.find().populate("affiliateId", "affiliateName affiliateCode").sort({ clickAt: -1 }).limit(1000) })));
affiliateMarketingRouter.get("/affiliate-marketing/purchases", asyncHandler(async (_req, res) => res.json({ success: true, data: await AffiliatePurchase.find().populate("affiliateId", "affiliateName affiliateCode").sort({ purchaseAt: -1 }).limit(1000) })));
affiliateMarketingRouter.get("/affiliate-marketing/settings", asyncHandler(async (_req, res) => res.json({ success: true, data: await settings() })));
affiliateMarketingRouter.patch("/affiliate-marketing/settings", asyncHandler(async (req, res) => { const old = await settings(); const value = await AffiliateSettings.findOneAndUpdate({ key: "default" }, { $set: req.body }, { new: true, runValidators: true }); await AffiliateAuditLog.create({ adminId: actor(req), action: "Affiliate Settings Changed", oldData: old, newData: value }); res.json({ success: true, data: value }); }));
affiliateMarketingRouter.get("/affiliate-marketing/audit-logs", asyncHandler(async (_req, res) => res.json({ success: true, data: await AffiliateAuditLog.find().sort({ createdAt: -1 }).limit(1000) })));
