import { Schema, model, models, baseJsonOptions } from "./base.js";

const affiliateSchema = new Schema({ firstName: String, lastName: String, affiliateName: { type: String, required: true }, email: { type: String, unique: true, lowercase: true }, mobile: String, username: { type: String, unique: true, lowercase: true }, passwordHash: { type: String, select: false }, profileImage: String, affiliateCode: { type: String, unique: true, uppercase: true }, referralLink: String, status: { type: String, enum: ["ACTIVE", "INACTIVE", "SUSPENDED"], default: "ACTIVE", index: true }, referralTarget: { type: Number, min: 1 }, commissionRatePercent: { type: Number, min: 0, max: 100 }, company: String, organization: String, profession: String, website: String, socialMediaLinks: Schema.Types.Mixed, address: String, city: String, state: String, country: String, pincode: String, description: String, accountHolderName: String, bankName: String, accountNumber: { type: String, select: false }, ifsc: String, upiId: String, pan: String, gst: String, profileCompletion: Number, notes: String, lastLoginAt: Date }, baseJsonOptions);
const referralSchema = new Schema({ affiliateId: { type: Schema.Types.ObjectId, ref: "Affiliate", index: true }, referralClickId: { type: String, unique: true, index: true }, affiliateCode: { type: String, index: true }, userId: { type: String, index: true }, campaign: { type: String, index: true }, affiliateLinkId: { type: String, index: true }, referralUrl: String, platform: { type: String, index: true }, deviceType: String, browser: String, osName: String, osVersion: String, appVersion: String, ipAddress: String, userAgent: String, clickStatus: { type: String, default: "CLICKED", index: true }, installationStatus: { type: String, default: "UNKNOWN", index: true }, registrationStatus: { type: String, default: "PENDING", index: true }, loginStatus: { type: String, default: "PENDING", index: true }, purchaseStatus: { type: String, default: "PENDING", index: true }, conversionStatus: { type: String, default: "PENDING", index: true }, userType: { type: String, default: "UNKNOWN", index: true }, attributionStatus: { type: String, default: "ACTIVE", index: true }, clickAt: { type: Date, default: Date.now, index: true }, expiresAt: Date, attributedAt: Date, registrationAt: Date, loginAt: Date, firstAppOpenAt: Date, purchaseAt: Date, subscriptionPlanId: String, purchaseAmount: Number, transactionId: { type: String, index: true }, paymentGateway: String, paymentStatus: String, subscriptionStatus: String, commissionRate: Number, commissionAmount: Number }, baseJsonOptions);
const purchaseSchema = new Schema({ affiliateId: { type: Schema.Types.ObjectId, ref: "Affiliate", index: true }, userId: String, referralId: Schema.Types.ObjectId, subscriptionId: String, planId: String, platform: { type: String, index: true }, transactionId: { type: String, unique: true, index: true }, paymentGateway: String, amount: Number, paymentStatus: { type: String, index: true }, subscriptionStatus: { type: String, index: true }, conversionStatus: { type: String, default: "SUCCESSFUL", index: true }, commissionStatus: { type: String, enum: ["PENDING", "PAID"], default: "PENDING", index: true }, commissionRate: Number, commissionAmount: Number, purchaseAt: { type: Date, index: true }, refundedAt: Date, commissionPaidAt: Date }, baseJsonOptions);
const settingsSchema = new Schema({ key: { type: String, default: "default", unique: true }, attributionWindowDays: { type: Number, default: 30 }, attributionModel: { type: String, enum: ["FIRST_CLICK", "LAST_CLICK"], default: "LAST_CLICK" }, allowExistingUserAttribution: { type: Boolean, default: true }, commissionRatePercent: { type: Number, default: 20, min: 0, max: 100 }, milestoneCount: { type: Number, default: 25 }, milestoneThresholds: { type: [Number], default: [25] }, repeatMilestone: { type: Boolean, default: true }, emailEnabled: { type: Boolean, default: true }, appNotificationEnabled: { type: Boolean, default: true }, adminEmail: String, referralBaseUrl: { type: String, default: "https://affiliateapi.kritamcqs.com/affiliatelink" } }, baseJsonOptions);
const auditSchema = new Schema({ adminId: String, affiliateId: Schema.Types.ObjectId, action: String, oldData: Schema.Types.Mixed, newData: Schema.Types.Mixed }, baseJsonOptions);
const affiliateNotificationSchema = new Schema({ affiliateId: { type: Schema.Types.ObjectId, ref: "Affiliate", index: true }, notificationType: String, title: String, message: String, reportData: Schema.Types.Mixed, emailStatus: { type: String, default: "PENDING" }, appNotificationStatus: { type: String, enum: ["SENT", "DELIVERED", "FAILED"], default: "SENT", index: true }, sentByAdminId: String, sentAt: Date, deliveredAt: Date, readAt: Date }, baseJsonOptions);
const adminNotificationSchema = new Schema({ type: { type: String, index: true }, title: String, message: String, affiliateId: { type: Schema.Types.ObjectId, ref: "Affiliate", index: true }, threshold: Number, purchaseCount: Number, status: { type: String, enum: ["UNREAD", "READ"], default: "UNREAD", index: true }, readAt: Date, metadata: Schema.Types.Mixed }, baseJsonOptions);
const paymentCycleSchema = new Schema({ affiliateId: { type: Schema.Types.ObjectId, ref: "Affiliate", required: true, index: true }, cycleNumber: { type: Number, required: true }, targetCount: { type: Number, required: true }, successfulReferralCount: { type: Number, default: 0 }, earnings: { type: Number, default: 0 }, purchaseIds: [{ type: Schema.Types.ObjectId, ref: "AffiliatePurchase" }], status: { type: String, enum: ["PENDING", "ELIGIBLE_FOR_PAYMENT", "PAYMENT_PROCESSING", "PAYMENT_SENT", "PAYMENT_COMPLETED", "FAILED", "CANCELLED"], default: "PENDING", index: true }, eligibleAt: Date, paymentDate: Date, completedAt: Date, statusHistory: [{ status: String, changedAt: Date, changedBy: String, note: String }] }, baseJsonOptions);
paymentCycleSchema.index({ affiliateId: 1, cycleNumber: 1 }, { unique: true });
const eventTemplateSchema = new Schema({ event: { type: String, required: true, unique: true, uppercase: true }, name: { type: String, required: true }, recipient: { type: String, enum: ["AFFILIATE", "ADMIN", "BOTH"], default: "AFFILIATE" }, notificationEnabled: { type: Boolean, default: true }, emailEnabled: { type: Boolean, default: true }, title: String, message: String, subject: String, htmlContent: String, textContent: String, variables: [String], updatedBy: String }, baseJsonOptions);

export const Affiliate = models.Affiliate || model("Affiliate", affiliateSchema);
export const AffiliateReferral = models.AffiliateReferral || model("AffiliateReferral", referralSchema);
export const AffiliatePurchase = models.AffiliatePurchase || model("AffiliatePurchase", purchaseSchema);
export const AffiliateSettings = models.AffiliateSettings || model("AffiliateSettings", settingsSchema);
export const AffiliateAuditLog = models.AffiliateAuditLog || model("AffiliateAuditLog", auditSchema);
export const AffiliateNotification = models.AffiliateNotification || model("AffiliateNotification", affiliateNotificationSchema);
export const AffiliateAdminNotification = models.AffiliateAdminNotification || model("AffiliateAdminNotification", adminNotificationSchema);
export const AffiliatePaymentCycle = models.AffiliatePaymentCycle || model("AffiliatePaymentCycle", paymentCycleSchema);
export const AffiliateEventTemplate = models.AffiliateEventTemplate || model("AffiliateEventTemplate", eventTemplateSchema);
