import { Schema, model, models, baseJsonOptions } from "./base.js";

const affiliateSchema = new Schema({ firstName: String, lastName: String, affiliateName: { type: String, required: true }, email: { type: String, unique: true, lowercase: true }, mobile: String, username: { type: String, unique: true, lowercase: true }, passwordHash: { type: String, select: false }, profileImage: String, affiliateCode: { type: String, unique: true, uppercase: true }, referralLink: String, status: { type: String, enum: ["ACTIVE", "INACTIVE", "SUSPENDED"], default: "ACTIVE", index: true }, company: String, organization: String, profession: String, website: String, address: String, city: String, state: String, country: String, pincode: String, profileCompletion: Number, notes: String, lastLoginAt: Date }, baseJsonOptions);
const referralSchema = new Schema({ affiliateId: { type: Schema.Types.ObjectId, ref: "Affiliate", index: true }, referralClickId: { type: String, unique: true, index: true }, affiliateCode: { type: String, index: true }, userId: { type: String, index: true }, campaign: { type: String, index: true }, affiliateLinkId: { type: String, index: true }, referralUrl: String, platform: { type: String, index: true }, deviceType: String, browser: String, osName: String, osVersion: String, appVersion: String, ipAddress: String, userAgent: String, clickStatus: { type: String, default: "CLICKED", index: true }, installationStatus: { type: String, default: "UNKNOWN", index: true }, registrationStatus: { type: String, default: "PENDING", index: true }, loginStatus: { type: String, default: "PENDING", index: true }, purchaseStatus: { type: String, default: "PENDING", index: true }, conversionStatus: { type: String, default: "PENDING", index: true }, userType: { type: String, default: "UNKNOWN", index: true }, attributionStatus: { type: String, default: "ACTIVE", index: true }, clickAt: { type: Date, default: Date.now, index: true }, expiresAt: Date, attributedAt: Date, registrationAt: Date, loginAt: Date, firstAppOpenAt: Date, purchaseAt: Date, subscriptionPlanId: String, purchaseAmount: Number, transactionId: { type: String, index: true }, paymentGateway: String, paymentStatus: String, subscriptionStatus: String, commissionRate: Number, commissionAmount: Number }, baseJsonOptions);
const purchaseSchema = new Schema({ affiliateId: { type: Schema.Types.ObjectId, ref: "Affiliate", index: true }, userId: String, referralId: Schema.Types.ObjectId, subscriptionId: String, planId: String, platform: { type: String, index: true }, transactionId: { type: String, unique: true, index: true }, paymentGateway: String, amount: Number, paymentStatus: { type: String, index: true }, subscriptionStatus: { type: String, index: true }, conversionStatus: { type: String, default: "SUCCESSFUL", index: true }, commissionRate: Number, commissionAmount: Number, purchaseAt: { type: Date, index: true }, refundedAt: Date }, baseJsonOptions);
const settingsSchema = new Schema({ key: { type: String, default: "default", unique: true }, attributionWindowDays: { type: Number, default: 30 }, attributionModel: { type: String, enum: ["FIRST_CLICK", "LAST_CLICK"], default: "LAST_CLICK" }, allowExistingUserAttribution: { type: Boolean, default: true }, commissionRatePercent: { type: Number, default: 20, min: 0, max: 100 }, milestoneCount: { type: Number, default: 10 }, repeatMilestone: { type: Boolean, default: true }, emailEnabled: { type: Boolean, default: true }, appNotificationEnabled: { type: Boolean, default: true }, adminEmail: String, referralBaseUrl: { type: String, default: "https://affiliateapi.kritamcqs.com/affiliatelink" } }, baseJsonOptions);
const auditSchema = new Schema({ adminId: String, affiliateId: Schema.Types.ObjectId, action: String, oldData: Schema.Types.Mixed, newData: Schema.Types.Mixed }, baseJsonOptions);

export const Affiliate = models.Affiliate || model("Affiliate", affiliateSchema);
export const AffiliateReferral = models.AffiliateReferral || model("AffiliateReferral", referralSchema);
export const AffiliatePurchase = models.AffiliatePurchase || model("AffiliatePurchase", purchaseSchema);
export const AffiliateSettings = models.AffiliateSettings || model("AffiliateSettings", settingsSchema);
export const AffiliateAuditLog = models.AffiliateAuditLog || model("AffiliateAuditLog", auditSchema);
