import { Schema, model, models, baseJsonOptions } from "./base.js";

const affiliateSchema = new Schema({ firstName: String, lastName: String, affiliateName: { type: String, required: true }, email: { type: String, unique: true, lowercase: true }, mobile: String, username: { type: String, unique: true, lowercase: true }, passwordHash: { type: String, select: false }, profileImage: String, affiliateCode: { type: String, unique: true, uppercase: true }, referralLink: String, status: { type: String, enum: ["ACTIVE", "INACTIVE", "SUSPENDED"], default: "ACTIVE", index: true }, company: String, organization: String, profession: String, website: String, address: String, city: String, state: String, country: String, pincode: String, profileCompletion: Number, notes: String, lastLoginAt: Date }, baseJsonOptions);
const referralSchema = new Schema({ affiliateId: { type: Schema.Types.ObjectId, ref: "Affiliate", index: true }, referralClickId: { type: String, unique: true }, affiliateCode: String, userId: { type: String, index: true }, platform: String, deviceType: String, clickAt: Date, registrationAt: Date, purchaseAt: Date, subscriptionPlanId: String, purchaseAmount: Number, paymentStatus: String, subscriptionStatus: String, conversionStatus: String }, baseJsonOptions);
const purchaseSchema = new Schema({ affiliateId: { type: Schema.Types.ObjectId, ref: "Affiliate", index: true }, userId: String, referralId: Schema.Types.ObjectId, subscriptionId: String, planId: String, platform: String, transactionId: { type: String, unique: true }, paymentGateway: String, amount: Number, paymentStatus: String, subscriptionStatus: String, purchaseAt: Date }, baseJsonOptions);
const settingsSchema = new Schema({ key: { type: String, default: "default", unique: true }, attributionWindowDays: { type: Number, default: 30 }, milestoneCount: { type: Number, default: 10 }, repeatMilestone: { type: Boolean, default: true }, emailEnabled: { type: Boolean, default: true }, appNotificationEnabled: { type: Boolean, default: true }, adminEmail: String, referralBaseUrl: { type: String, default: "https://app.kritamcqs.com/affiliate" } }, baseJsonOptions);
const auditSchema = new Schema({ adminId: String, affiliateId: Schema.Types.ObjectId, action: String, oldData: Schema.Types.Mixed, newData: Schema.Types.Mixed }, baseJsonOptions);

export const Affiliate = models.Affiliate || model("Affiliate", affiliateSchema);
export const AffiliateReferral = models.AffiliateReferral || model("AffiliateReferral", referralSchema);
export const AffiliatePurchase = models.AffiliatePurchase || model("AffiliatePurchase", purchaseSchema);
export const AffiliateSettings = models.AffiliateSettings || model("AffiliateSettings", settingsSchema);
export const AffiliateAuditLog = models.AffiliateAuditLog || model("AffiliateAuditLog", auditSchema);
