import { Schema, model, models, baseJsonOptions } from "./base.js";

const mockTestSchema = new Schema(
  {
    title: { type: String, required: true, trim: true },
    slug: { type: String, required: true, trim: true, unique: true, index: true },
    description: { type: String, trim: true },
    examType: { type: String, enum: ["NEET", "JEE", "BOTH"], required: true, index: true },
    patternPreset: { type: String, enum: ["NEET_REAL", "JEE_REAL", "CUSTOM"], default: "CUSTOM", index: true },
    durationMinutes: { type: Number, required: true, min: 1 },
    totalQuestions: { type: Number, required: true, min: 1 },
    maxScore: { type: Number, required: true, min: 1 },
    questionIds: { type: [String], default: [] },
    subjectIds: { type: [String], default: [] },
    chapterIds: { type: [String], default: [] },
    instructions: { type: [String], default: [] },
    marksPerQuestion: { type: Number, default: 4 },
    negativeMarks: { type: Number, default: 1 },
    markingSchemeVersion: { type: String, default: "v1" },
    markingScheme: { type: Schema.Types.Mixed },
    questionMarkingRules: { type: [Schema.Types.Mixed], default: [] },
    markingOverrideEnabled: { type: Boolean, default: false },
    predictionTitle: { type: String, trim: true },
    predictionDescription: { type: String, trim: true },
    availabilityMode: { type: String, enum: ["all", "day_wise", "week_wise"], default: "all" },
    availableDaysOfMonth: { type: [Number], default: [] },
    availableWeekdays: { type: [String], default: [] },
    totalAttemptQuestions: { type: Number, min: 1 },
    sectionGroups: { type: [Schema.Types.Mixed], default: [] },
    generationSource: { type: String, enum: ["manual", "auto"], default: "manual", index: true },
    generationConfig: { type: Schema.Types.Mixed },
    generationHistory: { type: [Schema.Types.Mixed], default: [] },
    randomizeQuestionOrder: { type: Boolean, default: true },
    freeAccessDurationValue: { type: Number, default: 1, min: 1 },
    freeAccessDurationUnit: { type: String, enum: ["days", "weeks", "months"], default: "days" },
    premiumDurationType: { type: String, enum: ["daily", "weekly", "monthly"], default: "daily" },
    premiumValidityDays: { type: Number, default: 1, min: 1 },
    autoDailyQuestionRearrangement: { type: Boolean, default: false },
    autoDailyQuestionGeneration: { type: Boolean, default: false },
    lastAutoGeneratedDateKey: { type: String, default: "" },
    isPremiumOnly: { type: Boolean, default: false, index: true },
    isActive: { type: Boolean, default: true, index: true },
  },
  baseJsonOptions,
);

mockTestSchema.index({ examType: 1, isActive: 1, createdAt: -1 });

export const MockTest = models.MockTest || model("MockTest", mockTestSchema);
