import { Schema, model, models, baseJsonOptions } from "./base.js";

const notificationHistorySchema = new Schema(
  {
    campaignName: { type: String, trim: true, default: "" },
    notificationType: { type: String, enum: ["standard", "remind_notify", "reminder_subscription"], default: "standard", index: true },
    deliveryType: { type: String, enum: ["notification", "email", "both"], default: "notification", index: true },
    title: { type: String, trim: true, default: "" },
    message: { type: String, default: "" },
    image: { type: String, trim: true, default: "" },
    deepLink: { type: String, trim: true, default: "/notifications" },
    ctaConfigId: { type: String, trim: true, default: "", index: true },
    ctaText: { type: String, trim: true, default: "" },
    targetScreen: { type: String, trim: true, default: "" },
    emailTemplateId: { type: String, trim: true, default: "" },
    emailTemplateKey: { type: String, trim: true, default: "" },
    emailSubject: { type: String, trim: true, default: "" },
    emailBody: { type: String, default: "" },
    targetType: { type: String, default: "all", index: true },
    selectedUsers: { type: [String], default: [] },
    category: { type: String, default: "custom", index: true },
    sound: { type: String, default: "default" },
    priority: { type: String, default: "high" },
    sentCount: { type: Number, default: 0 },
    successCount: { type: Number, default: 0 },
    failedCount: { type: Number, default: 0 },
    noTokenCount: { type: Number, default: 0 },
    emailSentCount: { type: Number, default: 0 },
    emailFailedCount: { type: Number, default: 0 },
    emailSkippedCount: { type: Number, default: 0 },
    logs: { type: [Schema.Types.Mixed], default: [] },
    status: { type: String, enum: ["draft", "scheduled", "sent", "failed", "partial"], default: "sent", index: true },
    createdBy: { type: String, default: "" },
    createdByName: { type: String, default: "" },
    sentAt: { type: Date },
    scheduledNotificationId: { type: Schema.Types.ObjectId, ref: "ScheduledNotification" },
  },
  baseJsonOptions,
);

export const NotificationHistory = models.NotificationHistory || model("NotificationHistory", notificationHistorySchema);
