import { Schema, model, models, baseJsonOptions } from "./base.js";

const revisionSettingsSchema = new Schema(
  {
    wrongQuestionLimit: { type: Number, default: 10, min: 1, max: 100 },
    oldQuestionLimit: { type: Number, default: 5, min: 1, max: 100 },
    dailyRevisionLimit: { type: Number, default: 20, min: 1, max: 200 },
    revisionEnabled: { type: Boolean, default: true },
    includeWrongQuestions: { type: Boolean, default: true },
    includeSkippedQuestions: { type: Boolean, default: true },
    includeLowAccuracyQuestions: { type: Boolean, default: true },
    includeWeakAreaQuestions: { type: Boolean, default: true },
    accuracyThreshold: { type: Number, default: 80, min: 0, max: 100 },
    minimumCorrectAnswers: { type: Number, default: 1, min: 0, max: 200 },
    completionAttemptCount: { type: Number, default: 1, min: 1, max: 20 },
    difficultyMode: { type: String, enum: ["easy", "medium", "moderate", "hard", "mixed"], default: "mixed" },
    scheduleMode: { type: String, enum: ["daily", "weekly", "custom"], default: "daily" },
    autoGeneratedRevisionTests: { type: Boolean, default: true },
    customRevisionQuestionIds: { type: [String], default: [] },
    subjectSettings: { type: Schema.Types.Mixed, default: {} },
    chapterSettings: { type: Schema.Types.Mixed, default: {} },
    topicSettings: { type: Schema.Types.Mixed, default: {} },
    spacedDays: {
      type: [Number],
      default: [1, 2, 5, 10],
      validate: {
        validator: (value) => Array.isArray(value) && value.length > 0 && value.every((day) => Number.isFinite(day) && day > 0),
        message: "spacedDays must contain one or more positive numbers",
      },
    },
  },
  baseJsonOptions,
);

export const RevisionSettings = models.RevisionSettings || model("RevisionSettings", revisionSettingsSchema);
